language: cpp
matrix:
    include:
        - name: linux and g++ (coverage)
          os: linux
          compiler: g++
          env: TARGET=coveragetest
          addons:
              apt:
                  packages:
                      - lcov
        - name: linux and g++
          os: linux
          compiler: g++
          env: TARGET=test
        - name: linux and clang
          os: linux
          compiler: clang
          env: TARGET=test
        - name: osx and g++
          os: osx
          compiler: g++
          env: TARGET=test
        - name: osx and clang
          os: osx
          compiler: clang
          env: TARGET=test
script: make $TARGET
before_install: if [ "$TARGET" = "coveragetest" ]; then pip install --user cpp-coveralls ; PARENTDIR=$(pwd) ; fi
after_success: if [ "$TARGET" = "coveragetest" ]; then cd $PARENTDIR/src ; lcov -t "result" -o coverage_out.info -c -d ./build/; lcov --remove coverage_out.info "/usr/include/*" -o coverage_out2.info; sed -i "s/SF:.*\/HiPPSO\/src\//SF:/" coverage_out2.info ; lcov --list coverage_out2.info; gem install coveralls-lcov ; ls ; pwd;  coveralls-lcov coverage_out2.info; fi
